name: Continuous Integration

on: 
  push:
    branches:
    - 'master'

jobs:
    ci:
        name: build and release docker latest image
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v2
          - name: build docker image
            run: make VERSION=latest image-linux
          - name: Login to DockerHub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Login to Github Packages
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
          - name: Push
            run: |
              docker push ghcr.io/studioetrange/docker-kcc:latest
              docker push studioetrange/docker-kcc:latest